# Generated by scripts/setup_venv.sh — from repo root: source ./env_local.sh
_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export HF_HOME="$_REPO/.cache"
export TRANSFORMERS_CACHE="$HF_HOME/hub"
export SENTENCE_TRANSFORMERS_HOME="$HF_HOME/sentence_transformers"
