#!/usr/bin/env bash
# Creates .venv at repo root, upgrades pip, installs requirements.txt.
# macOS / Linux: uses Python 3.12 when available (better PyTorch support); otherwise python3.
# Unlike scripts/setup_venv.ps1, CUDA wheels are NOT installed here — Apple Silicon uses MPS;
# follow https://pytorch.org/get-started/locally/ if you need a specific torch build.
# Writes env_local.sh so HF/transformers cache stays under ./.cache (optional).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

pick_python() {
  if command -v python3.12 >/dev/null 2>&1; then
    command -v python3.12
  elif command -v python3 >/dev/null 2>&1; then
    command -v python3
  else
    echo "ERROR: python3 not found. Install Python 3.10+ (3.12 recommended)." >&2
    exit 1
  fi
}

VENV_PY="$ROOT/.venv/bin/python"
if [[ ! -x "$VENV_PY" ]]; then
  PY="$(pick_python)"
  echo "Creating venv with: $PY"
  "$PY" -m venv .venv
  VENV_PY="$ROOT/.venv/bin/python"
fi

if [[ ! -x "$VENV_PY" ]]; then
  echo "ERROR: Expected Python at $VENV_PY" >&2
  exit 1
fi

"$VENV_PY" -m pip install --upgrade pip
"$VENV_PY" -m pip install -r "$ROOT/requirements.txt"

mkdir -p "$ROOT/.cache"

ENV_LOCAL="$ROOT/env_local.sh"
if [[ ! -f "$ENV_LOCAL" ]]; then
  cat >"$ENV_LOCAL" <<'EOF'
# Generated by scripts/setup_venv.sh — from repo root: source ./env_local.sh
_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export HF_HOME="$_REPO/.cache"
export TRANSFORMERS_CACHE="$HF_HOME/hub"
export SENTENCE_TRANSFORMERS_HOME="$HF_HOME/sentence_transformers"
EOF
  echo "Created env_local.sh (HF cache -> .cache/)."
fi

echo "Done. Optional GPU check: ./scripts/check_gpu.sh"
echo "Run: ./scripts/run_app.sh --reindex   or   ./scripts/run_web.sh"
