# Creates .venv next to the repo root, upgrades pip, installs requirements,
# then replaces the default CPU-only PyTorch wheel with a CUDA 12.4 build (NVIDIA GPU).
# PyTorch does not ship CUDA wheels for every Python version (e.g. 3.14 is often CPU-only) —
# this script prefers Python 3.12 when the "py" launcher is available.
# Also writes env_local.ps1 so HF/transformers cache stays under ./.cache (optional).
$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
Set-Location $Root

$VenvPy = Join-Path $Root ".venv\Scripts\python.exe"
$CreateVenv = $true
if (Test-Path $VenvPy) {
    $CreateVenv = $false
}

if ($CreateVenv) {
    if (Get-Command py -ErrorAction SilentlyContinue) {
        py -3.12 -c "import sys" 2>$null | Out-Null
        if ($LASTEXITCODE -eq 0) {
            Write-Host 'Creating venv with Python 3.12 (recommended for PyTorch + CUDA on Windows)...'
            py -3.12 -m venv .venv
        } else {
            Write-Warning 'Python 3.12 not found via py -3.12. Using default Python; GPU wheels may be unavailable (e.g. on 3.14+ install 3.12 from python.org).'
            py -m venv .venv
        }
    } else {
        Write-Warning 'Python launcher py not found. Using python for venv - install Python 3.12 for best GPU support.'
        python -m venv .venv
    }
    $VenvPy = Join-Path $Root ".venv\Scripts\python.exe"
}

if (-not (Test-Path $VenvPy)) {
    Write-Error "Expected Python at $VenvPy"
}

& $VenvPy -m pip install --upgrade pip
& $VenvPy -m pip install -r (Join-Path $Root "requirements.txt")

Write-Host 'Installing PyTorch with CUDA 12.4 for GPU inference (overrides CPU wheel from PyPI)...'
& $VenvPy -m pip uninstall -y torch 2>$null
& $VenvPy -m pip install torch --index-url https://download.pytorch.org/whl/cu124

Write-Host 'Optional GPU check: .\scripts\check_gpu.ps1'

$CacheDir = Join-Path $Root ".cache"
New-Item -ItemType Directory -Force -Path $CacheDir | Out-Null

$EnvLocal = Join-Path $Root "env_local.ps1"
if (-not (Test-Path $EnvLocal)) {
    $EnvLocalBody = @'
# Generated by scripts/setup_venv.ps1 - dot-source before manual runs: . .\env_local.ps1
$env:HF_HOME = Join-Path $PSScriptRoot '.cache'
$env:TRANSFORMERS_CACHE = Join-Path $env:HF_HOME 'hub'
$env:SENTENCE_TRANSFORMERS_HOME = Join-Path $env:HF_HOME 'sentence_transformers'
'@
    $EnvLocalBody | Set-Content -Path $EnvLocal -Encoding utf8
    Write-Host 'Created env_local.ps1 (HF cache -> .cache/).'
}

Write-Host 'Done. Run: .\scripts\run_app.ps1 --reindex   or   .\scripts\run_web.ps1'
